In [3]:
import pandas as pd
import numpy as np
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
df=pd.read_csv("Property_with_Feature_Engineering.csv")

In [5]:
df.head()

,property_id,location_id,page_url,property_type,price,price_bin,location,city,province_name,locality,...,area_marla,area_sqft,purpose,bedrooms,date_added,year,month,day,agency,agent
0,347795,8,https://www.zameen.com/Property/lahore_model_t...,House,220000000,Very High,Model Town,Lahore,Punjab,"Model Town, Lahore, Punjab",...,120.0,32670.12,For Sale,0,07-17-2019,2019,7,17,Real Biz International,Usama Khan
1,482892,48,https://www.zameen.com/Property/lahore_multan_...,House,40000000,Very High,Multan Road,Lahore,Punjab,"Multan Road, Lahore, Punjab",...,20.0,5445.02,For Sale,5,10-06-2018,2018,10,6,Khan Estate,mohsinkhan and B
2,555962,75,https://www.zameen.com/Property/eden_eden_aven...,House,9500000,Low,Eden,Lahore,Punjab,"Eden, Lahore, Punjab",...,9.0,2450.26,For Sale,3,07-03-2019,2019,7,3,Shahum Estate 2,"Babar Hameed, Raja Omar"
3,562843,3821,https://www.zameen.com/Property/gulberg_2_gulb...,House,125000000,Very High,Gulberg,Lahore,Punjab,"Gulberg, Lahore, Punjab",...,20.0,5445.02,For Sale,8,04-04-2019,2019,4,4,NaN,NaN
4,686990,3522,https://www.zameen.com/Property/allama_iqbal_t...,House,21000000,High,Allama Iqbal Town,Lahore,Punjab,"Allama Iqbal Town, Lahore, Punjab",...,11.0,2994.76,For Sale,6,04-04-2019,2019,4,4,NaN,NaN

In [2]:
df.info()

NameError: name 'df' is not defined

In [75]:
df.shape

(191393, 24)

In [76]:
df.isnull().sum()

property_id          0
location_id          0
page_url             0
property_type        0
price                0
price_bin            0
location             0
city                 0
province_name        0
locality             0
latitude             0
longitude            0
baths                0
area                 0
area_marla           0
area_sqft            0
purpose              0
bedrooms             0
date_added           0
year                 0
month                0
day                  0
agency           47379
agent            47380
dtype: int64

EDA
Now we explore the data and observe the feature which are more relative to each and important for our final Machine learning Model

In [9]:
# After exploring the feature it is observed that first two features are not relevant to ML property id, url, locationid,
# It is also observed that also the last  feature agent Name, Agency, year, month , day are also not relavant as it 
# the date of posting the add which is not to our need for current model
# so we are locking our dataframe to the relvant feature for now and explore more
df=df.iloc[:,3:]

In [10]:
df.head(50)

,property_type,price,price_bin,location,city,province_name,locality,latitude,longitude,baths,...,area_marla,area_sqft,purpose,bedrooms,date_added,year,month,day,agency,agent
0,House,220000000,Very High,Model Town,Lahore,Punjab,"Model Town, Lahore, Punjab",31.483869,74.325686,0,...,120.0,32670.12,For Sale,0,07-17-2019,2019,7,17,Real Biz International,Usama Khan
1,House,40000000,Very High,Multan Road,Lahore,Punjab,"Multan Road, Lahore, Punjab",31.431593,74.179980,5,...,20.0,5445.02,For Sale,5,10-06-2018,2018,10,6,Khan Estate,mohsinkhan and B
2,House,9500000,Low,Eden,Lahore,Punjab,"Eden, Lahore, Punjab",31.499348,74.416959,0,...,9.0,2450.26,For Sale,3,07-03-2019,2019,7,3,Shahum Estate 2,"Babar Hameed, Raja Omar"
3,House,125000000,Very High,Gulberg,Lahore,Punjab,"Gulberg, Lahore, Punjab",31.522069,74.355512,7,...,20.0,5445.02,For Sale,8,04-04-2019,2019,4,4,NaN,NaN
4,House,21000000,High,Allama Iqbal Town,Lahore,Punjab,"Allama Iqbal Town, Lahore, Punjab",31.506483,74.286017,5,...,11.0,2994.76,For Sale,6,04-04-2019,2019,4,4,NaN,NaN
5,House,52000000,Very High,Gulberg,Lahore,Punjab,"Gulberg, Lahore, Punjab",31.495909,74.350569,6,...,20.0,5445.02,For Sale,5,06-02-2019,2019,6,2,MATZ Services,Group Captain (R) Tajammul Baig
6,House,16500000,High,Military Accounts Housing Society,Lahore,Punjab,"Military Accounts Housing Society, Lahore, Punjab",31.421229,74.285560,7,...,8.0,2178.01,For Sale,6,07-03-2019,2019,7,3,NaN,NaN
7,House,32500000,High,EME Society,Lahore,Punjab,"EME Society, Lahore, Punjab",31.439978,74.209685,0,...,20.0,5445.02,For Sale,5,07-03-2019,2019,7,3,Sukhera Estate & Builders,Ahmed Sheraz Sukhera
8,House,31500000,High,EME Society,Lahore,Punjab,"EME Society, Lahore, Punjab",31.437744,74.213490,0,...,20.0,5445.02,For Sale,6,07-03-2019,2019,7,3,Sukhera Estate & Builders,Ahmed Sheraz Sukhera
9,House,40000000,Very High,Izmir Town,Lahore,Punjab,"Izmir Town, Lahore, Punjab",31.409106,74.181662,0,...,32.0,8712.03,For Sale,6,07-03-2019,2019,7,3,Sukhera Estate & Builders,Ahmed Sheraz Sukhera
10,House,13500000,Medium,Eden,Lahore,Punjab,"Eden, Lahore, Punjab",31.441113,74.239683,4,...,7.5,2041.88,For Sale,4,04-04-2019,2019,4,4,NaN,NaN
11,House,87500000,Very High,Upper Mall,Lahore,Punjab,"Upper Mall, Lahore, Punjab",31.542114,74.355898,5,...,24.0,6534.02,For Sale,4,06-30-2019,2019,6,30,Hamza Real Estate,Imran Shahad
12,House,8500000,Low,Park View Villas,Lahore,Punjab,"Park View Villas, Lahore, Punjab",31.450248,74.200931,4,...,5.0,1361.25,For Sale,4,07-22-2019,2019,7,22,NaN,NaN
13,House,16500000,High,Cavalry Ground,Lahore,Punjab,"Cavalry Ground, Lahore, Punjab",31.500557,74.367730,0,...,10.0,2722.51,For Sale,4,04-04-2019,2019,4,4,Rana Estate,Rana Shahzad
14,House,18500000,High,Bahria Town,Lahore,Punjab,"Bahria Town, Lahore, Punjab",31.381706,74.195294,0,...,10.0,2722.51,For Sale,0,07-04-2019,2019,7,4,Punjab Associates,Ch. Tariq Ali Ranjha
15,House,23500000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.537239,74.420211,4,...,10.0,2722.51,For Sale,4,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
16,House,22500000,High,Bedian Road,Lahore,Punjab,"Bedian Road, Lahore, Punjab",31.473474,74.429569,4,...,20.0,5445.02,For Sale,4,04-04-2019,2019,4,4,NaN,NaN
17,House,50000000,Very High,Agrics Town,Lahore,Punjab,"Agrics Town, Lahore, Punjab",31.441625,74.224648,7,...,18.0,4900.52,For Sale,6,07-10-2019,2019,7,10,NaN,NaN
18,House,39500000,Very High,Gulberg,Lahore,Punjab,"Gulberg, Lahore, Punjab",31.526312,74.347959,6,...,10.0,2722.51,For Sale,6,06-11-2019,2019,6,11,NaN,NaN
19,House,27500000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.533161,74.419481,5,...,12.0,3267.01,For Sale,4,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
20,House,40000000,Very High,Chaman Park,Lahore,Punjab,"Chaman Park, Lahore, Punjab",31.567912,74.399192,3,...,11.0,2994.76,For Sale,6,01-04-2019,2019,1,4,NaN,NaN
21,House,50000000,Very High,Upper Mall,Lahore,Punjab,"Upper Mall, Lahore, Punjab",31.542114,74.355898,6,...,20.0,5445.02,For Sale,5,07-03-2019,2019,7,3,Hamza Real Estate,Imran Shahad
22,House,45000000,Very High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.537239,74.420211,6,...,20.0,5445.02,For Sale,5,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
23,House,3200000,Low,Chungi Amar Sadhu,Lahore,Punjab,"Chungi Amar Sadhu, Lahore, Punjab",31.450925,74.354287,2,...,3.0,816.75,For Sale,3,12-05-2018,2018,12,5,NaN,NaN
24,House,21200000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.536068,74.408666,4,...,10.0,2722.51,For Sale,3,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
25,House,23000000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.537458,74.413323,5,...,10.0,2722.51,For Sale,4,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
26,House,21500000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.533270,74.413580,5,...,10.0,2722.51,For Sale,4,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
27,House,21500000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.533161,74.419481,5,...,10.0,2722.51,For Sale,4,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
28,House,40000000,Very High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.537458,74.413323,6,...,20.0,5445.02,For Sale,5,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
29,House,26000000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.533161,74.419481,5,...,10.0,2722.51,For Sale,4,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
30,House,21000000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.537458,74.413323,4,...,10.0,2722.51,For Sale,4,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
31,House,23000000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.533270,74.413580,5,...,10.0,2722.51,For Sale,4,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
32,House,23000000,High,Askari,Lahore,Punjab,"Askari, Lahore, Punjab",31.533161,74.419481,6,...,10.0,2722.51,For Sale,5,06-18-2019,2019,6,18,Forces Properties,Khalid Saeed Khan
33,House,57500000,Very High,EME Society,Lahore,Punjab,"EME Society, Lahore, Punjab",31.439978,74.209685,5,...,20.0,5445.02,For Sale,5,04-03-2019,2019,4,3,Punjaab Estates,Irfan Rehman Khan
34,House,620000000,Very High,GOR,Lahore,Punjab,"GOR, Lahore, Punjab",31.543431,74.344225,8,...,130.0,35392.63,For Sale,8,05-03-2019,2019,5,3,Punjaab Estates,Irfan Rehman Khan
35,House,5500000,Low,Karim Park,Lahore,Punjab,"Karim Park, Lahore, Punjab",31.590234,74.300365,3,...,2.5,680.63,For Sale,3,06-11-2019,2019,6,11,NaN,NaN
36,House,50000000,Very High,Gulberg,Lahore,Punjab,"Gulberg, Lahore, Punjab",31.538420,74.352357,6,...,20.0,5445.02,For Sale,5,07-03-2019,2019,7,3,Hamza Real Estate,Imran Shahad
37,House,12000000,Medium,Cantt,Lahore,Punjab,"Cantt, Lahore, Punjab",31.498580,74.409270,6,...,8.0,2178.01,For Sale,6,12-05-2018,2018,12,5,NaN,NaN
38,House,65000000,Very High,Valencia Housing Society,Lahore,Punjab,"Valencia Housing Society, Lahore, Punjab",31.405370,74.257078,0,...,40.0,10890.04,For Sale,0,06-02-2019,2019,6,2,Punjaab Estates,Irfan Rehman Khan
39,House,1250000000,Very High,Gulberg,Lahore,Punjab,"Gulberg, Lahore, Punjab",31.519435,74.345548,0,...,160.0,43560.16,For Sale,0,02-03-2019,2019,2,3,Punjaab Estates,Irfan Rehman Khan
40,House,42500000,Very High,Gulshan-e-Ravi,Lahore,Punjab,"Gulshan-e-Ravi, Lahore, Punjab",31.551184,74.284058,8,...,22.0,5989.52,For Sale,8,04-04-2019,2019,4,4,NaN,NaN
41,House,66500000,Very High,Valencia Housing Society,Lahore,Punjab,"Valencia Housing Society, Lahore, Punjab",31.400096,74.259682,0,...,40.0,10890.04,For Sale,0,04-03-2019,2019,4,3,Punjaab Estates,Irfan Rehman Khan
42,House,12000000,Medium,Al-Raheem Garden,Lahore,Punjab,"Al-Raheem Garden, Lahore, Punjab",31.597234,74.474513,5,...,6.0,1633.51,For Sale,5,07-03-2019,2019,7,3,NaN,NaN
43,House,40000000,Very High,EME Society,Lahore,Punjab,"EME Society, Lahore, Punjab",31.437744,74.213490,7,...,20.0,5445.02,For Sale,6,04-04-2019,2019,4,4,NaN,NaN
44,House,180000000,Very High,Gulberg,Lahore,Punjab,"Gulberg, Lahore, Punjab",31.505678,74.348202,7,...,94.0,25591.59,For Sale,5,07-03-2019,2019,7,3,Hamza Real Estate,Imran Shahad
45,House,17000000,High,Mateen Avenue,Lahore,Punjab,"Mateen Avenue, Lahore, Punjab",31.441992,74.291389,6,...,9.7,2640.83,For Sale,5,03-05-2019,2019,3,5,NaN,NaN
46,House,47500000,Very High,EME Society,Lahore,Punjab,"EME Society, Lahore, Punjab",31.434668,74.214005,0,...,20.0,5445.02,For Sale,0,05-03-2019,2019,5,3,Punjaab Estates,Irfan Rehman Khan
47,House,17000000,High,Paragon City,Lahore,Punjab,"Paragon City, Lahore, Punjab",31.530739,74.456184,5,...,10.0,2722.51,For Sale,5,06-11-2019,2019,6,11,Valo Marketing,Nabeel Khalid Ch M Naveed Muhammad Bin Shahid
48,House,25000000,High,IEP Engineers Town,Lahore,Punjab,"IEP Engineers Town, Lahore, Punjab",31.402513,74.292798,5,...,18.0,4900.52,For Sale,4,02-01-2019,2019,2,1,NaN,NaN
49,House,17600000,High,Bahria Town,Lahore,Punjab,"Bahria Town, Lahore, Punjab",31.374195,74.191482,6,...,10.0,2722.51,For Sale,5,05-03-2019,2019,5,3,NaN,NaN

In [20]:
df.shape

(191393, 15)

In [21]:
df.head()

,property_type,price,price_bin,location,city,province_name,locality,latitude,longitude,baths,area,area_marla,area_sqft,purpose,bedrooms
0,House,220000000,Very High,Model Town,Lahore,Punjab,"Model Town, Lahore, Punjab",31.483869,74.325686,0,6 Kanal,120.0,32670.12,For Sale,0
1,House,40000000,Very High,Multan Road,Lahore,Punjab,"Multan Road, Lahore, Punjab",31.431593,74.179980,5,1 Kanal,20.0,5445.02,For Sale,5
2,House,9500000,Low,Eden,Lahore,Punjab,"Eden, Lahore, Punjab",31.499348,74.416959,0,9 Marla,9.0,2450.26,For Sale,3
3,House,125000000,Very High,Gulberg,Lahore,Punjab,"Gulberg, Lahore, Punjab",31.522069,74.355512,7,1 Kanal,20.0,5445.02,For Sale,8
4,House,21000000,High,Allama Iqbal Town,Lahore,Punjab,"Allama Iqbal Town, Lahore, Punjab",31.506483,74.286017,5,11 Marla,11.0,2994.76,For Sale,6

In [22]:
# for in depth anaylsis of correlation with head
df.corr()

,price,latitude,longitude,baths,area_marla,area_sqft,bedrooms
price,1.000000,-0.084885,-0.049790,0.219297,0.021809,0.021809,0.303069
latitude,-0.084885,1.000000,0.915495,0.047043,0.008298,0.008298,0.025288
longitude,-0.049790,0.915495,1.000000,0.090028,0.007487,0.007487,0.072582
baths,0.219297,0.047043,0.090028,1.000000,0.004605,0.004605,0.669057
area_marla,0.021809,0.008298,0.007487,0.004605,1.000000,1.000000,0.007573
area_sqft,0.021809,0.008298,0.007487,0.004605,1.000000,1.000000,0.007573
bedrooms,0.303069,0.025288,0.072582,0.669057,0.007573,0.007573,1.000000

In [23]:
# now we explore the property type feature 
df["property_type"].value_counts()

House            118915
Flat              40157
Upper Portion     18475
Lower Portion     11693
Room               1029
Farm House          725
Penthouse           399
Name: property_type, dtype: int64

In [24]:
#As observed the porperty_type feature is Nominal Categorical feature 
# So we can apply OneHotEncoding prepare it for ML
property_type=pd.get_dummies(df["property_type"], drop_first=True)

In [82]:
property_type.head()

   Flat  House  Lower Portion  Penthouse  Room  Upper Portion
0     0      1              0          0     0              0
1     0      1              0          0     0              0
2     0      1              0          0     0              0
3     0      1              0          0     0              0
4     0      1              0          0     0              0

In [25]:
#Now we explore the price_bin feature
# As depth analysis this feature is ordinal categorical value the higher the price the price bin is high value
df["price_bin"].value_counts()

Low          50175
High         48112
Medium       46978
Very High    46128
Name: price_bin, dtype: int64

In [26]:
# now replacing the categorical value with numerical value
df.replace({"Low":0, "Medium":1, "High":2, "Very High":3 }, inplace=True)

In [27]:
df.head()

,property_type,price,price_bin,location,city,province_name,locality,latitude,longitude,baths,area,area_marla,area_sqft,purpose,bedrooms
0,House,220000000,3,Model Town,Lahore,Punjab,"Model Town, Lahore, Punjab",31.483869,74.325686,0,6 Kanal,120.0,32670.12,For Sale,0
1,House,40000000,3,Multan Road,Lahore,Punjab,"Multan Road, Lahore, Punjab",31.431593,74.179980,5,1 Kanal,20.0,5445.02,For Sale,5
2,House,9500000,0,Eden,Lahore,Punjab,"Eden, Lahore, Punjab",31.499348,74.416959,0,9 Marla,9.0,2450.26,For Sale,3
3,House,125000000,3,Gulberg,Lahore,Punjab,"Gulberg, Lahore, Punjab",31.522069,74.355512,7,1 Kanal,20.0,5445.02,For Sale,8
4,House,21000000,2,Allama Iqbal Town,Lahore,Punjab,"Allama Iqbal Town, Lahore, Punjab",31.506483,74.286017,5,11 Marla,11.0,2994.76,For Sale,6

In [28]:
# now we explore the city 
df["city"].value_counts()

Karachi       60484
Lahore        58736
Islamabad     40195
Rawalpindi    22898
Faisalabad     9080
Name: city, dtype: int64

In [29]:
# As we explore we find the city feature as Nominal value 
# so we apply One hot Encoding
city=pd.get_dummies(df["city"],drop_first=True)

In [30]:
city.head()

   Islamabad  Karachi  Lahore  Rawalpindi
0          0        0       1           0
1          0        0       1           0
2          0        0       1           0
3          0        0       1           0
4          0        0       1           0

In [31]:
# now we explore the province the province feature
# we apply the same as city feature 
province=pd.get_dummies(df["province_name"],drop_first=True)

In [32]:
province.head()

   Punjab  Sindh
0       1      0
1       1      0
2       1      0
3       1      0
4       1      0